### ISSUE TITLE
 Request for Zonestar Z8XR2 Firmware Source Code and ZRIB 5.5 Motherboard Pin Configuration

### ISSUE THREAD

**Issue by Vlad-bi** [ZONESTAR3D/source-code-for-3d-printer#4]
Hello!

Back in 2018 I purchased a Zonestar Z8XR2 3D printer, which came installed with a ZRIB 5.5 motherboard. Since then, I've made several modifications to the printer, and I'm currently in the process of updating the firmware to accommodate these changes.

However, I've run into an issue as I can't seem to locate the pin configuration for the ZRIB 5.5 motherboard, which is integral to my firmware modifications. I've searched extensively but haven't been able to find the necessary resources or documentation.

Additionally, if anyone has access to the original source code for the Zonestar Z8XR2's firmware, that would be tremendously helpful in my current task.

Any assistance or guidance on this matter would be greatly appreciated. Thank you in advance for your time and support.

**Comment by ZONESTAR3D** [comment]
Hello,
Z8XR2 is a product end of produce 3 years ago, please download it from here:
https://github.com/ZONESTAR3D/Firmware/tree/master/backup/Sourcecode

PS: we will also upload a config for Z8XR2 here later, please check again after 2 to 3 days.
